# fly.toml file generated for account-management on 2023-02-23T20:57:29-08:00

app = "account-management"
kill_signal = "SIGINT"
kill_timeout = 2
processes = []

[build]
  builder = "paketobuildpacks/builder:base"
  buildpacks = ["gcr.io/paketo-buildpacks/go"]

[env]
  PORT = "8080"
  POSTGRES_HOST = "account-management-db.internal"
  POSTGRES_PORT = "5432"
  POSTGRES_USER = "postgres"
  POSTGRES_DB = "account_management"
  POSTGRES_PASSWORD = "XbpFZYVeADBJ6wR"
  ORIGIN = "https://account-management-27654.web.app"
  BASE_URL = ""

[experimental]
  auto_rollback = true

[[services]]
  http_checks = []
  internal_port = 8080
  processes = ["app"]
  protocol = "tcp"
  script_checks = []
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = false
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"
